Nameless_Store/Controllers/NamelessStoreCartController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Nameless_Store.Models;

namespace Nameless_Store.Controllers
{
    public class NamelessStoreCartController : Controller
    {
        private Nameless_StoreContext db = new Nameless_StoreContext();

        // GET: NamelessStoreCRUD
        public ActionResult Index()
        {
            return View(db.NamelessStoreModels.ToList());
        }

        // GET: NamelessStoreCRUD/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NamelessStoreModel namelessStoreModel = db.NamelessStoreModels.Find(id);
            if (namelessStoreModel == null)
            {
                return HttpNotFound();
            }
            return View(namelessStoreModel);
        }

        // GET: NamelessStoreCRUD/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: NamelessStoreCRUD/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Price")] NamelessStoreModel namelessStoreModel)
        {
            if (ModelState.IsValid)
            {
                db.NamelessStoreModels.Add(namelessStoreModel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(namelessStoreModel);
        }

        // GET: NamelessStoreCRUD/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NamelessStoreModel namelessStoreModel = db.NamelessStoreModels.Find(id);
            if (namelessStoreModel == null)
            {
                return HttpNotFound();
            }
            return View(namelessStoreModel);
        }

        // POST: NamelessStoreCRUD/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Price")] NamelessStoreModel namelessStoreModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(namelessStoreModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(namelessStoreModel);
        }

        // GET: NamelessStoreCRUD/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NamelessStoreModel namelessStoreModel = db.NamelessStoreModels.Find(id);
            if (namelessStoreModel == null)
            {
                return HttpNotFound();
            }
            return View(namelessStoreModel);
        }

        // POST: NamelessStoreCRUD/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            NamelessStoreModel namelessStoreModel = db.NamelessStoreModels.Find(id);
            db.NamelessStoreModels.Remove(namelessStoreModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Nameless_Store/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Cars And Autoparts<table style="width:100%;"><tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr><tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr><tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr></table></title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nameless Store - Cars And Autoparts", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Cart", "Index", "NamelessStoreCart")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Nameless Store - Cars And AutoParts</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>